version: '2.1'
services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    depends_on:
      - postgresdb
    volumes:
      - .:/go/src/github.com/CarsonBull/mobileCICD/scheduler
    environment:
      - DB_URL=postgresdb
      - DB_PORT=5432
      - SSL=disable
      - ENV=dev
    networks:
      - backend


  postgresdb:
    image: postgres
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
    networks:
      - backend

networks:
  backend:
